### PR TITLE
Added AppCompat version as a separate artifact

### PR DESCRIPTION
**Pull request by consp1racy**
### But why?

AppCompat keeps backporting features of TextView into AppCompatTextView and these were not available to HtmlTextView. I was mostly interested in color theme attribute resolution (from API 24).

### Why not just one artifact for everything?

Some Samsung devices with Android 4.4 could crash if this library had a compile time dependency on AppCompat but the app didn't depend on AppCompat. No child of `View` can reference a class not on classpath.

### What's the catch?

Sadly, `AppCompatHtmlTextView` cannot be casted to `HtmlTextView`.

### CODE REVIEW

**Comment by dschuermann** [comment]
Haven't yet thought about this PR, because it makes the library structure more complicated :(

**Comment by consp1racy** [comment]
Would it be easier if there was just one artifact? My original assessment about 

> Some Samsung devices with Android 4.4 could crash if this library had a compile time dependency on AppCompat but the app didn't depend on AppCompat. No child of View can reference a class not on classpath.

was wrong.

**Comment by dschuermann** [comment]
@consp1racy Yep, this would drastically simplify this PR. I think the additional dependency on AppCompat should be no problem as everyone uses it nowadays.

**Comment by consp1racy** [comment]
The actual AppCompat dependency may be `provided` or `compileOnly` in that regard.

Alright, I'll get to it.

**Pull request closed without merging**
